version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123        
      MYSQL_DATABASE: mydb               
      MYSQL_USER: user                   
      MYSQL_PASSWORD: pass123            
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
volumes:
  mysql_data:
